OUTCOMES :
Defining a matrix
idenenty zero one matrix 
addition multiplication substraction 
transpose determinant
decompostion of a matrix into lower and upper 
solving a equation using scipy.linalg.solve function

In [5]:
import numpy as np


In [21]:
matrix = np.array([  [1,2,3],[4,5,6],[7,8,9]  ])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0.]
 [0. 0.]]


IDENTITY ZERO AND ONE MATRIX

In [33]:
matrix2=np.ones((2,2))
print(matrix2)


matrix3=np.zeros((2,2))
print(matrix3)


matrix4=np.eye(4) //only one parameter needed as at is identity

print(matrix4)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


MULTIPLICATIN ADDITION AND SUBSTRACTION 

In [57]:
new=matrix2+matrix2
print(new)

new2=matrix2*matrix2
print(new2)



[[2. 2.]
 [2. 2.]]
[[1. 1.]
 [1. 1.]]


In [83]:
new=np.array([[1,2,3],[4,5,6]])
print(new)

newT=new.T
print(newT)



[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


DETERMINANT OF A MATIX  ----- LINALG NEW LIBRARY

In [85]:
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

Determinant: -9.51619735392994e-16


INVERSE OF A MATRIX

In [ ]:
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse) 

SOLVING A SYSTEM OF LINEAR EQUATION , for finding X and Y value of a equation

In [97]:
A=np.array([[1,2],[3,4]])
B=np.array([8,11])

X=np.linalg.solve(A,B)

print(X)

[-5.   6.5]


In [116]:
from scipy.linalg import lu

P, L, U = lu(matrix)

print("P (Permutation matrix):\n", P)
print("   ")
print("L (Lower triangular):\n", L)
print("   ")
print("U (Upper triangular):\n", U)

P (Permutation matrix):
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
   
L (Lower triangular):
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
   
U (Upper triangular):
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


EIGENVALUES AND EIGEN VECTORS

In [130]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

eigenvalues , eigenvectors=np.linalg.eig(matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


We can reconstruct A using:

ini
Copy
Edit
A = V * D * V⁻¹
Where:

V = matrix of eigenvectors

D = diagonal matrix of eigenvalues

V⁻¹ = inverse of eigenvector matrix

python
Copy
Edit
# Form the diagonal matrix of eigenvalues
D = np.diag(eigenvalues)

# Inverse of eigenvector matrix
V_inv = np.linalg.inv(eigenvectors)

# Reconstruct A
A_reconstructed = eigenvectors @ D @ V_inv

print("Reconstructed A:\n", A_reconstructed)

<!-- # Vector  -->

In [ ]:
# ## Summary
# Operation	Code Example	Result
# Vector Addition	v1 + v2	[3, 3, 3]
# Dot Product	np.dot(v1, v2)	-2
# Cross Product	np.cross(v1, v2)	[-3, 6, -3]
# Vector Norm	np.linalg.norm(v1)	~5.385
# Normalization	v1 / np.linalg.norm(v1)	Unit vector

🎯 What PCA does:
Centers the data (subtract the mean)

Finds the best direction where the data spreads the most → This is the first principal component

Projects the data onto that line (reducing 2D → 1D)

In [141]:
import numpy as np
from sklearn.decomposition import PCA

# Sample 2D dataset
X = np.array([
    [2.5, 2.4],
    [0.5, 0.7],
    [2.2, 2.9],
    [1.9, 2.2],
    [3.1, 3.0]
])

# Apply PCA to reduce to 1D
pca = PCA(n_components=1)
X_pca = pca.fit_transform(X)

print("Original shape:", X.shape)
print("Reduced shape:", X_pca.shape)
print("Transformed data:\n", X_pca)


Original shape: (5, 2)
Reduced shape: (5, 1)
Transformed data:
 [[ 0.44362444]
 [-2.17719404]
 [ 0.57071239]
 [-0.12902465]
 [ 1.29188186]]
